version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assignmentai
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - assignmentai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - assignmentai-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assignmentai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assignmentai-network

volumes:
  postgres_data:

networks:
  assignmentai-network:
    driver: bridge
