global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"

  - job_name: "celery"
    static_configs:
      - targets: ["flower:5555"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
