# Traefik Configuration for AssignmentAI Production
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: app-network

certificatesResolvers:
  myresolver:
    acme:
      email: ${ACME_EMAIL}
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

middlewares:
  auth:
    basicAuth:
      users:
        - 'admin:$$2y$$10$${GRAFANA_PASSWORD_HASH}'
  security:
    headers:
      frameDeny: true
      sslRedirect: true
      browserXssFilter: true
      contentTypeNosniff: true
      forceSTSHeader: true
      stsIncludeSubdomains: true
      stsPreload: true
      stsSeconds: 31536000
      customFrameOptionsValue: 'SAMEORIGIN'
      customRequestHeaders:
        X-Forwarded-Proto: 'https'
  rate-limit:
    rateLimit:
      burst: 100
      average: 50
  cors:
    headers:
      accessControlAllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      accessControlAllowHeaders:
        - Authorization
        - Content-Type
        - X-Requested-With
      accessControlAllowOriginList:
        - 'https://assignmentai.app'
        - 'https://www.assignmentai.app'
      accessControlMaxAge: 86400
      addVaryHeader: true
