"""Add AI feedback and assignment generation models

Revision ID: 006677cb9e4f
Revises: 7b60d87b9f88
Create Date: 2025-03-30 16:39:26.003044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006677cb9e4f'
down_revision = '7b60d87b9f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemlog_id'), 'systemlog', ['id'], unique=False)
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_table('system_logs')
    op.add_column('assignments', sa.Column('class_id', sa.Integer(), nullable=False))
    op.create_index('idx_assignment_class', 'assignments', ['class_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index('idx_assignment_class', table_name='assignments')
    op.drop_column('assignments', 'class_id')
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_systemlog_id'), table_name='systemlog')
    op.drop_table('systemlog')
    # ### end Alembic commands ###
