"""update_activity_model_fields

Revision ID: 0c48e33c14af
Revises: 55516d1c902f
Create Date: 2025-07-07 17:46:08.291227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c48e33c14af'
down_revision = '55516d1c902f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('action', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('resource_type', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('resource_id', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('user_agent', sa.String(), nullable=True))
    op.alter_column('activities', 'activity_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_activities_type', table_name='activities')
    op.create_index('ix_activities_action', 'activities', ['action'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.drop_column('activities', 'type')
    op.drop_column('activities', 'title')
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_action', table_name='activities')
    op.create_index('ix_activities_type', 'activities', ['type'], unique=False)
    op.alter_column('activities', 'activity_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('activities', 'user_agent')
    op.drop_column('activities', 'ip_address')
    op.drop_column('activities', 'resource_id')
    op.drop_column('activities', 'resource_type')
    op.drop_column('activities', 'action')
    # ### end Alembic commands ###
