"""add user_id to ai_assignments

Revision ID: 55516d1c902f
Revises: 26e3cd6fbdc4
Create Date: 2025-07-06 22:51:03.495550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55516d1c902f'
down_revision = '26e3cd6fbdc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make all new columns nullable for migration to succeed
    op.add_column('ai_assignments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('ai_assignments', sa.Column('model', sa.String(length=50), nullable=True))
    op.add_column('ai_assignments', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_assignments', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('ai_assignments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('ai_assignments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ai_assignments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_assignments', 'generated_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_assignments', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('idx_ai_assignment_status', 'ai_assignments', ['status'], unique=False)
    op.create_index('idx_ai_assignment_user', 'ai_assignments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_assignments', 'users', ['user_id'], ['id'])
    # NOTE: After migration, backfill columns and set NOT NULL if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_assignments', type_='foreignkey')
    op.drop_index('idx_ai_assignment_user', table_name='ai_assignments')
    op.drop_index('idx_ai_assignment_status', table_name='ai_assignments')
    op.alter_column('ai_assignments', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ai_assignments', 'generated_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ai_assignments', 'updated_at')
    op.drop_column('ai_assignments', 'created_at')
    op.drop_column('ai_assignments', 'status')
    op.drop_column('ai_assignments', 'temperature')
    op.drop_column('ai_assignments', 'max_tokens')
    op.drop_column('ai_assignments', 'model')
    op.drop_column('ai_assignments', 'user_id')
    # ### end Alembic commands ###
