"""create users table

Revision ID: 578e9bd88c14
Revises: a8c3d6aab89e
Create Date: 2025-06-23 16:40:16.254555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578e9bd88c14'
down_revision = 'a8c3d6aab89e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
