"""add_token_balance_to_user_model

Revision ID: a8c3d6aab89e
Revises: cf73953395df
Create Date: 2025-06-23 16:35:53.331330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c3d6aab89e'
down_revision = 'cf73953395df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_balance', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_balance')
    # ### end Alembic commands ###
