"""update_transactions_created_at_to_timezone_aware

Revision ID: a9df0f18c5cd
Revises: 021b9af6d5f9
Create Date: 2025-09-21 16:02:32.373749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9df0f18c5cd'
down_revision = '021b9af6d5f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_expires', table_name='tokens')
    op.drop_index('idx_token_user_type', table_name='tokens')
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=False)
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.create_index('idx_token_user_type', 'tokens', ['user_id', 'token_type'], unique=False)
    op.create_index('idx_token_expires', 'tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
