"""Add device_key field to UserSession for session deduplication

Revision ID: b783f329c906
Revises: ee821189a449
Create Date: 2025-08-18 17:12:31.222145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b783f329c906'
down_revision = 'ee821189a449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_token_expires', table_name='tokens')
    op.drop_index('idx_token_user_type', table_name='tokens')
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.drop_table('tokens')
    op.drop_column('preferences', 'email_notifications')
    op.drop_column('preferences', 'push_notifications')
    op.drop_column('preferences', 'notification_types')
    op.add_column('user_sessions', sa.Column('device_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_sessions_device_key'), 'user_sessions', ['device_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_device_key'), table_name='user_sessions')
    op.drop_column('user_sessions', 'device_key')
    op.add_column('preferences', sa.Column('notification_types', sqlite.JSON(), nullable=True))
    op.add_column('preferences', sa.Column('push_notifications', sa.BOOLEAN(), nullable=True))
    op.add_column('preferences', sa.Column('email_notifications', sa.BOOLEAN(), nullable=True))
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=False)
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.create_index('idx_token_user_type', 'tokens', ['user_id', 'token_type'], unique=False)
    op.create_index('idx_token_expires', 'tokens', ['expires_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('notification_metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
