"""remove_canvas_fields

Revision ID: c5d5c47b6dfb
Revises: 0cab33a8b1a8
Create Date: 2025-07-07 19:42:35.430273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d5c47b6dfb'
down_revision = '0cab33a8b1a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'canvas_institution')
    op.drop_column('users', 'canvas_refresh_token')
    op.drop_column('users', 'canvas_user_id')
    op.drop_column('users', 'canvas_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('canvas_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('canvas_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('canvas_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('canvas_institution', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
