"""Add stripe_customer_id to user model

Revision ID: cf73953395df
Revises: 7d7554bc44c5
Create Date: 2025-06-22 19:46:06.109913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf73953395df'
down_revision = '7d7554bc44c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
